---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:jquijino/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image:
      image: jquijino/podinfo:dev-remr1rw3
#      repository: jquijino/podinfo
#      tag: dev-remr1rw3
    replicaCount: 1
    hpa:
      enabled: false
